import { useState } from "react";
import { Inbox, Plus, Upload } from "lucide-react";
import { apiFetch, readApiJson } from "../../api/client";
import { field, message, primary, secondary, type InboxBooking, type ToolRecord } from "./types";

const blank: InboxBooking = { title: "", kind: "stay", reference: "", start_date: "", end_date: "", time: "", address: "", notes: "", status: "draft" };
export function BookingInbox({ tripId, records, save, remove, busy }: { tripId: string; records: ToolRecord[]; save: (id: string, type: "inbox", data: InboxBooking) => Promise<void>; remove: (id: string) => Promise<void>; busy: boolean }) {
  const [draft, setDraft] = useState<InboxBooking | null>(null), [identity, setIdentity] = useState("");
  const [raw, setRaw] = useState(""), [filename, setFilename] = useState("");
  const [error, setError] = useState(""), [extracting, setExtracting] = useState(false), [notice, setNotice] = useState("");
  const entries = records.filter((r): r is ToolRecord & { type: "inbox"; data: InboxBooking } => r.type === "inbox");
  const start = () => { setDraft({ ...blank }); setIdentity(`tool-${crypto.randomUUID()}`); setError(""); setNotice(""); };
  return <div className="space-y-6"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="text-xs uppercase tracking-widest text-[#e8cd95]">Everything in one place</p><h3 className="mt-2 text-2xl">Your booking inbox</h3></div><button className={primary} onClick={start}><Plus className="mr-2 inline" size={16} />Add booking</button></div>
    <p className="text-sm text-slate-300">Review confirmations here. Payments and selected offers stay unchanged.</p>
    {error && <p role="alert" className="text-amber-100">{error}</p>}
    {notice && <p role="status" className="text-[#91e4db]">{notice}</p>}
    {draft && <form className="space-y-4 rounded-2xl border border-[#e8cd95]/30 bg-[#16282b] p-4 sm:p-6" onSubmit={async e => { e.preventDefault(); setError(""); try { await save(identity, "inbox", draft); setDraft(null); setRaw(""); setNotice("Booking saved. No payment or selection was changed."); } catch (e) { setError(message(e)); } }}>
      <details><summary className="min-h-11 cursor-pointer py-3 text-[#e8cd95]"><Upload size={16} className="mr-2 inline" />Import a confirmation</summary><p className="text-sm text-slate-300">Paste text or upload .txt / .eml (100 KB max). PDF and image extraction are not supported yet; enter those details below.</p>
        <label className="mt-3 block text-sm">Confirmation file<input className={field} type="file" accept=".txt,.eml,text/plain,message/rfc822" onChange={async e => { const file = e.target.files?.[0]; if (!file) return; if (file.size > 100_000 || !/\.(txt|eml)$/i.test(file.name)) { setError("Choose a .txt or .eml file under 100 KB."); return; } try { setRaw(await file.text()); setFilename(file.name); setError(""); } catch (e) { setError(message(e)); } }} /></label>
        <label className="mt-3 block text-sm">Confirmation text<textarea className={field} value={raw} maxLength={100_000} onChange={e => { setRaw(e.target.value); setFilename(""); }} /></label>
        <button type="button" className={`${secondary} mt-3`} disabled={extracting || !raw.trim()} onClick={async () => { setExtracting(true); setError(""); try { const result = await readApiJson<{ draft: Partial<InboxBooking>; notice: string }>(await apiFetch(`/api/trips/${tripId}/booking-inbox/extract`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ text: raw, filename }) })); setDraft({ ...draft, ...result.draft, status: "draft" }); setNotice(result.notice); } catch (e) { setError(message(e)); } finally { setExtracting(false); } }}>{extracting ? "Reading…" : "Extract for review"}</button>
      </details>
      <div className="grid gap-4 sm:grid-cols-2"><label className="text-sm">Booking name<input required maxLength={120} className={field} value={draft.title} onChange={e => setDraft({ ...draft, title: e.target.value })} /></label><label className="text-sm">Type<select className={field} value={draft.kind} onChange={e => setDraft({ ...draft, kind: e.target.value })}>{["stay", "flight", "activity", "transport", "other"].map(v => <option key={v}>{v}</option>)}</select></label>
        {(["reference", "start_date", "end_date", "time", "address"] as const).map(key => <label key={key} className="text-sm">{{ reference: "Confirmation reference", start_date: "Start date", end_date: "End date", time: "Local time", address: "Address or airport" }[key]}<input type={key.includes("date") ? "date" : key === "time" ? "time" : "text"} maxLength={key === "address" ? 300 : 120} className={field} value={draft[key]} onChange={e => setDraft({ ...draft, [key]: e.target.value })} /></label>)}
        <label className="text-sm">Status<select aria-label="Status" className={field} value={draft.status} onChange={e => setDraft({ ...draft, status: e.target.value as InboxBooking["status"] })}><option value="draft">Draft · needs review</option><option value="confirmed">Confirmed by me</option><option value="cancelled">Cancelled by me</option></select></label>
      </div><label className="block text-sm">Notes<textarea className={field} maxLength={1000} value={draft.notes} onChange={e => setDraft({ ...draft, notes: e.target.value })} /></label><div className="flex flex-wrap gap-3"><button className={primary} disabled={busy || extracting}>{busy ? "Saving…" : "Save reviewed booking"}</button><button type="button" className={secondary} onClick={() => setDraft(null)}>Cancel</button></div>
    </form>}
    {!entries.length && !draft && <div className="rounded-2xl border border-dashed border-white/25 p-8 text-center"><Inbox className="mx-auto text-[#e8cd95]" /><p className="mt-3 text-lg">Less searching through emails.</p><p className="mt-2 text-sm text-slate-300">Add your first booking to keep its details close.</p></div>}
    <div className="grid gap-4 sm:grid-cols-2">{entries.map(entry => <article key={entry.id} className="rounded-2xl border border-white/15 bg-white/5 p-5"><p className="text-xs uppercase tracking-widest text-[#e8cd95]">{entry.data.kind} · {entry.data.status === "confirmed" ? "Confirmed by you" : entry.data.status}</p><h4 className="mt-3 text-xl">{entry.data.title}</h4><p className="mt-2 text-sm text-slate-300">{entry.data.start_date || "Date not recorded"} {entry.data.time}</p><p className="mt-2 font-mono text-sm">{entry.data.reference || "No reference"}</p><p className="mt-2 text-sm text-slate-300">{entry.data.address}</p><div className="mt-4 flex gap-3"><button className={secondary} onClick={() => { setIdentity(entry.id); setDraft({ ...entry.data }); setNotice(""); }}>Review</button><button className={secondary} disabled={busy} onClick={async () => { if (!window.confirm("Remove this inbox entry? This does not cancel the booking.")) return; try { await remove(entry.id); } catch (e) { setError(message(e)); } }}>Remove</button></div></article>)}</div>
  </div>;
}
